export const mockVacancies = [
  {
    id: '1',
    title: 'Frontend-разработчик',
    salary: '100 000 - 150 000 ₽',
    experience: 'Опыт 1-3 года',
    format: 'Можно удалённо',
    company: 'Kata Academy',
    city: 'Москва',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '2',
    title: 'React Developer',
    salary: 'от 180 000 ₽',
    experience: 'От 3 до 6 лет',
    format: 'Гибрид',
    company: 'VK',
    city: 'Санкт-Петербург',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '3',
    title: 'Junior Frontend-разработчик',
    salary: 'от 90 000 ₽',
    experience: 'Без опыта',
    format: 'Офис',
    company: 'T-Банк',
    city: 'Москва',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '4',
    title: 'Frontend Engineer',
    salary: 'от 160 000 до 210 000 ₽',
    experience: 'Опыт 1-3 года',
    format: 'Можно удалённо',
    company: 'Яндекс',
    city: 'Москва',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '5',
    title: 'React / TypeScript Developer',
    salary: 'от 200 000 ₽',
    experience: 'От 3 до 6 лет',
    format: 'Гибрид',
    company: 'Ozon',
    city: 'Санкт-Петербург',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '6',
    title: 'Middle Frontend Developer',
    salary: '130 000 - 170 000 ₽',
    experience: 'Опыт 1-3 года',
    format: 'Офис',
    company: 'Авито',
    city: 'Москва',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '7',
    title: 'Frontend-разработчик React',
    salary: 'от 140 000 ₽',
    experience: 'Опыт 1-3 года',
    format: 'Можно удалённо',
    company: 'Сбер',
    city: 'Москва',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '8',
    title: 'Middle React Developer',
    salary: 'от 190 000 ₽',
    experience: 'От 3 до 6 лет',
    format: 'Гибрид',
    company: 'Wildberries',
    city: 'Санкт-Петербург',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '9',
    title: 'Frontend Developer',
    salary: '120 000 - 160 000 ₽',
    experience: 'Опыт 1-3 года',
    format: 'Офис',
    company: 'Lamoda',
    city: 'Москва',
    vacancyUrl: 'https://hh.ru',
  },
  {
    id: '10',
    title: 'TypeScript Frontend Engineer',
    salary: 'от 220 000 ₽',
    experience: 'От 3 до 6 лет',
    format: 'Можно удалённо',
    company: 'Контур',
    city: 'Санкт-Петербург',
    vacancyUrl: 'https://hh.ru',
  },
];
